### ISSUE TITLE
Daraja API implementation

### ISSUE THREAD

**Issue by kamaubrian** [malcolmmaima/Dishi#1]
Can payments be done directly from the app to a paybill or a till number, that would be awesome.

**Comment by malcolmmaima** [comment]
That's the last module i'll implement....it's my understanding that for me to setup Daraja API ... I need to get a paybill number which is a process and needs a business certificate. I'm trying to explore easier ways of doing this even if it will mean asking around my circles who have a paybill number i can use to test.

The way I've setup the app, especially the cart module should allow easy integration... I'm currently working on uber style tracking where provider with a nduthi can be seen moving towards the customer.
